#!/usr/bin/env python
import os
import sys

libname = "rcbeam"
godot_cpp_dir = ARGUMENTS.get("godot_cpp_dir", os.path.join(os.getcwd(), "godot-cpp"))

if not os.path.isdir(godot_cpp_dir):
    print("godot-cpp not found at: {}".format(godot_cpp_dir))
    print("Clone godotengine/godot-cpp there, or pass godot_cpp_dir=/path/to/godot-cpp")
    Exit(1)

local_env = Environment(tools=["default"], PLATFORM="")
opts = Variables()
opts.Update(local_env)
env = local_env.Clone()

# godot-cpp v10 can target Godot 4.7 explicitly.
env = SConscript(
    os.path.join(godot_cpp_dir, "SConstruct"),
    {"api_version": "4.7", "env": env, "customs": []},
)

env.Append(CPPPATH=[
    "src",
    "../include",
])

sources = Glob("src/*.cpp")
sources.append("../src/solver.cpp")

suffix = env["suffix"].replace(".dev", "").replace(".universal", "")
lib_filename = "{}{}{}{}".format(
    env.subst("$SHLIBPREFIX"),
    libname,
    suffix,
    env.subst("$SHLIBSUFFIX"),
)

library = env.SharedLibrary(
    "bin/{}/{}".format(env["platform"], lib_filename),
    source=sources,
)

Default(library)
